

### Keyboard name
# 1 nice
CONFIG_ZMK_KEYBOARD_NAME="Corne Fran"


### Boost Bluetooth TX power, also make Bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Tune bluetooth profiles for quick select
CONFIG_BT_MAX_CONN=5

### POWER OPTIONS
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_SLEEP=y
# 2 puchi 1 min (15*60*1000ms)
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000

# Disable external power when not connected to USB
#CONFIG_ZMK_EXT_POWER_USB_ONLY=y

### OLED Display - nice!view
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y

### WIDGET SETTINGS compatible SOLO con OLED
CONFIG_ZMK_WIDGET_WPM_STATUS=n
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y

### HID para nice!view ePaperDisplay
# Enable eager debouncing
# "Eager Debouncing"
# Trying to lower the input lag.
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=0

CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

### Improves compatibility with iPad
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y